apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  labels:
    app: react-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-image
  template:
    metadata:
      labels:
        app: react-image
    spec:
      containers:
      - name: reactserver
        image: ramikhreim/react-image
        ports:
        - containerPort: 3000