apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: react-image
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110