export const projects = [
  {
    title: 'MERN Memories',
    description: "Using React, Node.js, Express & MongoDB you'll learn how to build a Full Stack MERN Application - from start to finish. The App is called Memories and it is a simple social media app that allows users to post interesting events that happened in their lives.",
      image: '/images/1.png',
      tags: ['Mongo', 'Express', 'React', 'Node'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'E-Commerce',
    description:"While building it you're going to learn many advanced React & JavaScript topics, as well as how to use Stripe for card transactions. On top of that, at the end of the video, you will have this unique and complex webshop app that you will be able to add to your portfolio. And trust me, e-commerce applications are impressive.",
    image: '/images/2.png',
    tags: ['React', 'JavaScript'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'WebRTC App',
    description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
      image: '/images/3.jpg',
      tags: ['React', 'WebRTC'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Fitness Exercises App',
    description: "This is a code repository i used APIs from RapidAPIs ,create the best and most modern Fitness Exercises App using two separate APIs. ExerciseDB and Youtube Search and Download APIs, host the website on AWS Amplify or netlify.com  .",
      image: '/images/3.png',
      tags: ['React', 'RapidAPI','AWS Amplify'],
    source: 'https://jowry.click',
    visit: 'https://github.com/ramikhreim1',
    id: 2,
  },
  {
    title: 'Unichat',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/4.jpg',
    tags: ['React', 'ChatEngine', 'Firebase'],
    source: 'https://jowry.click',
    visit: 'https://github.com/ramikhreim1/project_fitness',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2000, text: 'Started my journey', },
  { year: 2005, text: 'Worked as IT Manager', },
  { year: 2012, text: 'Network Operation Center Manager', },
  { year: 2015, text: 'Senior Cloud Specialist', },
  { year: 2019, text: 'Cloud Platform Development Operations', },
];